services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'rvvup_hyva_data_mariadb:/bitnami/mariadb'
  magento:
    ports:
      - '89:8080'
      - '8443:8443'
    environment:
      - BITNAMI_DEBUG=true
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MAGENTO_HOST=local.dev.rvvuptech.com:89
      - MAGENTO_USERNAME=admin
      - MAGENTO_PASSWORD=password1
      - MAGENTO_EMAIL=admin@test.com
      - RVVUP_API_KEY=$RVVUP_API_KEY
      - RVVUP_HYVA_CHECKOUT_VERSION=$RVVUP_HYVA_CHECKOUT_VERSION
      - MAGENTO_REPO_PUBLIC_KEY=$MAGENTO_REPO_PUBLIC_KEY
      - MAGENTO_REPO_PRIVATE_KEY=$MAGENTO_REPO_PRIVATE_KEY
      - HYVA_SSH_PRIVATE_KEY=$HYVA_SSH_PRIVATE_KEY
      - MAGENTO_SMTP_HOST=mailpit
      - MAGENTO_SMTP_PORT=1025
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAGENTO_VERSION: $MAGENTO_VERSION
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'rvvup_hyva_elasticsearch_data:/bitnami/elasticsearch/data'
  mailpit:
    image: docker.io/axllent/mailpit:v1.24
    ports:
      - '9925:8025'
volumes:
  rvvup_hyva_data_mariadb:
    driver: local
  rvvup_hyva_elasticsearch_data:
    driver: local
