<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var \Rvvup\PaymentsHyvaCheckout\Magewire\Checkout\Payment\ApplePayProcessor $magewire */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div id="rvvup-apple-pay-inline" data-quoteamount="<?php echo $magewire->quoteAmount; ?>" data-quotecurrency="<?php echo $magewire->quoteCurrency; ?>">
    <script>
        hyvaCheckout.api.after(() => {
            const blockName = '<?= $escaper->escapeJs($block->getNameInLayout()) ?>';
            const divId = "rvvup-apple-pay-button";
            let $showApplePay = true;
            let $applePaySelected = false;
            let applePay = null;
            let applePayReady = false;

            const applePayOption = document.getElementById('payment-method-option-rvvup_APPLE_PAY');
            if (applePayOption) {
                applePayOption.style.display = 'block';
            }

            const getQuoteTotal = () => {
                const dataSet = document.querySelector('#rvvup-apple-pay-inline').dataset;
                return {
                    amount: dataSet.quoteamount,
                    currency: dataSet.quotecurrency
                };
            };
            const triggerApplePayDisplayEvent = () => {
                if (!$showApplePay) {
                    window.dispatchEvent(new CustomEvent('rvvup:methods:apple-pay:hide'));
                }
            };

            const renderApplePayButton = async () => {
                if (!applePayReady || applePay === null || document.getElementById(divId)) {
                    return;
                }
                const placeOrderButton = getPlaceOrderButton();
                if (!placeOrderButton) {
                    return;
                }
                const applePayButtonDiv = document.createElement('div');
                applePayButtonDiv.id = divId;
                applePayButtonDiv.className = 'rvvup-applepay-button z-0';
                if (placeOrderButton.className && placeOrderButton.className.indexOf("w-full") > -1) {
                    applePayButtonDiv.className += ' w-full';
                }
                placeOrderButton.parentNode.insertBefore(applePayButtonDiv, placeOrderButton);
                await applePay.mount({
                    selector: "#" + divId,
                });
            };

            const removeApplePayButton = () => {
                const applePayButtonDiv = document.getElementById(divId);
                if (applePayButtonDiv) {
                    applePayButtonDiv.remove();
                }
            };

            window.rvvup_sdk.createPaymentMethod("APPLE_PAY", {
                checkoutSessionKey: rvvup_parameters.checkout.token,
                total: getQuoteTotal(),
            }).then(method => {
                applePay = method;
                applePay.on("ready", async () => {
                    applePayReady = true;
                    if ($applePaySelected) {
                        await renderApplePayButton();
                    }
                    $showApplePay = await applePay.canMakePayment();
                    triggerApplePayDisplayEvent();
                });
                applePay.on("click", () => {
                    applePay.update({total: getQuoteTotal()});
                });
                applePay.on("beforePaymentAuth", async () => {
                    const component = Magewire.find(blockName);
                    await component.createPaymentSession(rvvup_parameters.checkout.id)
                    return {
                        paymentSessionId: component.paymentSessionResult.paymentSessionId
                    };
                });
                applePay.on("paymentAuthorized", () => {
                    const component = Magewire.find(blockName);
                    window.rvvupLoader?.show();
                    window.location.href = component.paymentSessionResult.redirectUrl;
                });
                applePay.on("paymentFailed", (data) => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: 'error',
                        text: 'Payment ' + data.reason
                    }], 5000);
                });
            }).catch(e => {
                console.error("Error creating Apple Pay payment method", e);
            });

            window.addEventListener('checkout:step:loaded', () => {
                triggerApplePayDisplayEvent();
                if ($applePaySelected) {
                    renderApplePayButton();
                }
            });
            window.addEventListener('rvvup:methods:apple-pay:hide', () => {
                let element = document.getElementById("payment-method-option-rvvup_APPLE_PAY");
                if (element) {
                    element.parentElement.removeChild(element);
                }
            });

            hyvaCheckout.payment.registerMethod({
                code: 'rvvup_APPLE_PAY',

                method: {
                    initialize: async function () {
                        $applePaySelected = true;
                        triggerApplePayDisplayEvent();
                        const placeOrderButton = getPlaceOrderButton();
                        if (placeOrderButton) {
                            placeOrderButton.classList.add('rvvup_APPLE_PAY_place_order_button');
                        }
                        await renderApplePayButton();
                    },

                    uninitialize: async function () {
                        $applePaySelected = false;
                        const placeOrderButton = getPlaceOrderButton();
                        if (placeOrderButton) {
                            placeOrderButton.classList.remove('rvvup_APPLE_PAY_place_order_button');
                        }
                        removeApplePayButton();
                    },

                    placeOrder: async function () {
                        return Magewire.find(blockName).placeOrder();
                    }
                }
            });
        });
    </script>
<?php $hyvaCsp->registerInlineScript() ?>
</div>
