<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div wire:ignore>
    <script>
        hyvaCheckout.api.after(() => {
            const blockName = '<?= $escaper->escapeJs($block->getNameInLayout()) ?>';
            const applePayOption = document.getElementById('payment-method-option-rvvup_APPLE_PAY');
            if (applePayOption) {
                applePayOption.style.display = 'none';
            }

            function enableApplePay() {
                let applePay = document.getElementById('payment-method-option-rvvup_APPLE_PAY');
                if (applePay && window.ApplePaySession && window.ApplePaySession.canMakePayments()) {
                    applePay.style.display = 'block';
                }
            }

            enableApplePay();
            window.addEventListener('magewire:update', () => {
                enableApplePay();
            }, {once: false});

            hyvaCheckout.payment.registerMethod({
                code: 'rvvup_APPLE_PAY',

                method: {
                    placeOrder: async function () {
                        return Magewire.find(blockName).placeOrder();
                    }
                }
            });
        });
    </script>
<?php $hyvaCsp->registerInlineScript() ?>
</div>
