<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div wire:ignore>
<script>
    (() => {
        window.addEventListener('checkout:payment:method-activate', event => {
            if (event.detail.method !== 'rvvup_APPLE_PAY') {
                return;
            }

            const component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
            hyvaCheckout.payment.activate('rvvup_APPLE_PAY', {
                placeOrderViaJs() {
                    return true;
                },

                isVisibleInStep() {
                    return hyvaCheckout.main.getElement().contains(this.el)
                        && document.querySelector('[wire\\:key="rvvup_APPLE_PAY"].active')
                },

                placeOrder() {
                    return component.placeOrder();
                }
            }, document.querySelector('[wire\\:key="rvvup_APPLE_PAY"].active'));
        });
    })();
</script>
</div>
