<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div wire:ignore>
    <style>
        #payment-method-option-rvvup_APPLE_PAY {
            display: none;
        }
    </style>
    <script>
        (() => {
            window.addEventListener('checkout:payment:method-activate', event => {
                if (event.detail.method !== 'rvvup_APPLE_PAY') {
                    return;
                }

                const component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                hyvaCheckout.payment.activate('rvvup_APPLE_PAY', {
                    placeOrderViaJs() {
                        return document.querySelector('[wire\\:key="rvvup_APPLE_PAY"].active') !== null;
                    },

                    placeOrder() {
                        return component.placeOrder();
                    }
                }, document.querySelector('[wire\\:key="rvvup_APPLE_PAY"].active'));
            });
            enableApplePay();
            window.addEventListener('magewire:update', () => {
                enableApplePay();
            }, {once: false});

            function enableApplePay() {
                let applePay = document.getElementById('payment-method-option-rvvup_APPLE_PAY');
                if (applePay && window.ApplePaySession && window.ApplePaySession.canMakePayments()) {
                    applePay.style.display = 'block';
                }
            }
        })();
    </script>
<?php $hyvaCsp->registerInlineScript() ?>
</div>
