<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Rvvup\PaymentsHyvaCheckout\Block\Checkout\Payment\Assets $block */
?>

<?php foreach ($block->getAssets() as $asset): ?>
    <script type="text/javascript"
            src="<?= $escaper->escapeHtmlAttr($asset['url']) ?>"
            <?php
            foreach ($asset['attributes'] as $name => $value) {
                if ($value === null) {
                    echo $escaper->escapeHtmlAttr($name);
                    continue;
                }
                echo $escaper->escapeHtmlAttr($name) . '="' . $escaper->escapeHtmlAttr($value) . '"';
            }
            ?>
    ></script>
<?php endforeach; ?>
<script>
    function getPlaceOrderButtons() {
        // Hyva Checkout Version 1.2.0 or later had a checkout UX/UI upgrade
        let placeOrderButtons = document.querySelectorAll('.checkout-nav-main button');
        // Backwards compatibility for Hyva Checkout Version 1.1.29 or earlier
        if (placeOrderButtons.length === 0) {
            return document.querySelectorAll('.nav-main .btn-primary');
        }
        return placeOrderButtons
    }

    function getPlaceOrderButton() {
        let placeOrderButtons = getPlaceOrderButtons();
        if (placeOrderButtons.length > 0) {
            return placeOrderButtons[0];
        }
        return undefined;
    }
</script>