<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var \Rvvup\PaymentsHyvaCheckout\Magewire\Checkout\Payment\CardProcessor $magewire */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div wire:ignore>
    <script>
        (() => {
            window.addEventListener('checkout:payment:method-activate', event => {
                if (event.detail.method !== 'rvvup_CARD') {
                    return;
                }

                hyvaCheckout.payment.activate('rvvup_CARD', {
                    placeOrderViaJs() {
                        return document.querySelector('[wire\\:key="rvvup_CARD"].active') !== null;
                    },

                    placeOrder() {
                        const component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                        return component.placeOrder();
                    }
                }, document.querySelector('[wire\\:key="rvvup_CARD"].active'));
            });
        })();
    </script>
<?php $hyvaCsp->registerInlineScript() ?>
</div>
