<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var \Rvvup\PaymentsHyvaCheckout\Magewire\Checkout\Payment\CardProcessor $magewire */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div wire:ignore>
    <script>
        (() => {
            let ST = null;

            window.addEventListener('checkout:validation:success', () => {
                const component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                let magewire = document.getElementById('magewire-loader');
                magewire.children[0].style.display = 'block';

                component.loadPaymentActions().then(() => {
                    if (!component.paymentActions || !component.paymentActions.authorization) {
                        document.getElementById('magewire-loader').children[0].style.display = 'none';
                        return;
                    }
                    ST.updateJWT(component.paymentActions.authorization.value);
                    document.getElementById('tp_place_order').click();
                });
            });

            window.addEventListener('checkout:payment:method-activate', async event => {
                if (event.detail.method !== 'rvvup_CARD') {
                    return;
                }

                /*
                This code finds the magewire component, but the workaround is required because the component may not be
                immediately available when the script is executed. This is related to an issue in Hyva Checkout 1.3.0 or
                later. This is currently the suggested workaround provided by Hyva:
                https://gitlab.hyva.io/hyva-checkout/checkout/-/issues/418
                 */
                let component;
                try {
                    component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                } catch (error) {
                    await Livewire.onLoad(() => {
                        component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                    });
                }
                hyvaCheckout.payment.activate('rvvup_CARD', {
                    initialize() {
                        ST = SecureTrading({
                            jwt: '<?= $magewire->getInitializationToken() ?>',
                            animatedCard: true,
                            livestatus: <?= $magewire->getLiveStatus() ?>,
                            buttonId: "tp_place_order",
                            deferInit: true,
                            submitOnSuccess: false,
                            panIcon: true,
                            stopSubmitFormOnEnter: true,
                            formId: "st-form",
                            submitCallback: function (data) {
                                let threeD = data.threedresponse || null;
                                let authorization = data.jwt;

                                component.handleCallback(authorization, threeD);
                            },
                            errorCallback: function () {
                                /** Hide loader */
                                document.getElementById('magewire-loader').children[0].style.display = 'none';
                                var url = window.BASE_URL + 'rvvup/payment/cancel' + '?form_key=' + hyva.getFormKey();
                                fetch(
                                    url,
                                    {
                                        method: 'post',
                                        headers: {contentType: 'application/json'}
                                    }
                                )
                            },
                            translations: {
                                "Card number": '<?php echo $magewire->getTranslation('label', 'cardNumber', 'Card Number'); ?>',
                                "Expiration date": '<?php echo $magewire->getTranslation('label', 'expiryDate', 'Expiration Date'); ?>',
                                "Security code": '<?php echo $magewire->getTranslation('label', 'securityCode', 'Security Code'); ?>',
                                Pay: '<?php echo $magewire->getTranslation('button', 'pay', 'Pay'); ?>',
                                Processing: '<?php echo $magewire->getTranslation('button', 'processing', 'Processing'); ?>',
                                "Field is required":
                                    '<?php echo $magewire->getTranslation('error', 'fieldRequired', 'Field is required'); ?>',
                                "Value is too short":
                                    '<?php echo $magewire->getTranslation('error', 'valueTooShort', 'Value is too short'); ?>',
                                "Value mismatch pattern":
                                    '<?php echo $magewire->getTranslation('error', 'valueMismatch', 'Value is invalid'); ?>',
                            },
                            styles: {
                                "background-color-input": "#FFFFFF",
                                "border-color-input": "#EBEBF2",
                                "border-radius-input": "8px",
                                "border-size-input": "1px",
                                "color-input": "#050505",
                                "border-color-input-error": "#ff4545",
                                "color-label": "#050505",
                                "position-left-label": "0.5rem",
                                "font-size-label": "1.2rem",
                                "font-size-message": "1rem",
                                "space-outset-message": "0rem 0px 0px 0.5rem",
                            },
                        });

                        ST.Components();
                    },

                    placeOrderViaJs() {
                        return document.querySelector('[wire\\:key="rvvup_CARD"].active') !== null;
                    },

                    placeOrder() {
                        return component.placeOrder();
                    }
                }, document.querySelector('[wire\\:key="rvvup_CARD"].active'));
            });
        })();
    </script>
<?php $hyvaCsp->registerInlineScript() ?>
</div>
