<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var \Rvvup\PaymentsHyvaCheckout\Magewire\Checkout\Payment\CardProcessor $magewire */
?>
<div wire:ignore>
<script>
    (() => {
        window.addEventListener('checkout:payment:method-activate', event => {
            if (event.detail.method !== 'rvvup_CARD') {
                return;
            }

            const component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
            hyvaCheckout.payment.activate('rvvup_CARD', {
                placeOrderViaJs() {
                    return true;
                },

                placeOrder() {
                    component.loadPaymentActions().then(() => {
                        window.dispatchEvent(new CustomEvent('rvvup:update:showModal', {
                            detail: {
                                redirectUrl: component.paymentActions.capture.value
                            }
                        }))
                    });
                },
            }, document.querySelector('[wire\\:key="rvvup_CARD"].active'));
        });
    })();
</script>
</div>
