<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div wire:ignore>
<script>
    (() => {
        window.addEventListener('checkout:payment:method-activate', async event => {
            if (event.detail.method !== 'rvvup_FAKE_PAYMENT_METHOD') {
                return;
            }

            /*
            This code finds the magewire component, but the workaround is required because the component may not be
            immediately available when the script is executed. This is related to an issue in Hyva Checkout 1.3.0 or
            later. This is currently the suggested workaround provided by Hyva:
            https://gitlab.hyva.io/hyva-checkout/checkout/-/issues/418
             */
            let component;
            try {
                component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
            } catch (error) {
                await Livewire.onLoad(() => {
                    component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                });
            }
            hyvaCheckout.payment.activate('rvvup_FAKE_PAYMENT_METHOD', {
                placeOrderViaJs() {
                    return document.querySelector('[wire\\:key="rvvup_FAKE_PAYMENT_METHOD"].active') !== null;
                },

                placeOrder() {
                    return component.placeOrder();
                }
            }, document.querySelector('[wire\\:key="rvvup_FAKE_PAYMENT_METHOD"].active'));
        });
    })();
</script>
<?php $hyvaCsp->registerInlineScript() ?>
</div>
