<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div wire:ignore>
<script>
    hyvaCheckout.api.after(() => {
        hyvaCheckout.payment.registerMethod({
            code: 'rvvup_KLARNA',

            method: {
                placeOrder: async function () {
                    return Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>').placeOrder();
                }
            }
        });
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>
</div>
