<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
?>
<div
    id="rvvup-loader"
    x-data="rvvupCheckoutLoader"
>
    <?= /** @noEscape */ $block->getChildHtml('loading') ?>
</div>
<script>
    function rvvupCheckoutLoader() {
        return {
            isLoading: false,
        };
    }

    window.rvvupLoader = {
        setLoading(isLoading) {
            const element = document.getElementById('rvvup-loader');
            if (element && window.Alpine) {
                window.Alpine.$data(element).isLoading = isLoading;
            }
        },
        show() {
            this.setLoading(true);
        },
        hide() {
            this.setLoading(false);
        },
    };

    (() => {
        const register = () => Alpine.data('rvvupCheckoutLoader', rvvupCheckoutLoader);
        window.Alpine ? register() : window.addEventListener('alpine:init', register, {once: true});
    })();
</script>
<?php $hyvaCsp->registerInlineScript() ?>
