<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Rvvup\PaymentsHyvaCheckout\Magewire\Checkout\Payment\RvvupExpressProcessor;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var RvvupExpressProcessor $magewire */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */

?>
<div wire:ignore>
    <div x-data="rvvupExpressButtons"
         x-init="initRvvup"
         class="rvvup_express_container hidden flex flex-col items-center justify-center w-full mb-2.5">
        <div class="rvvup_express_title rvvup_express_text_with_line my-5 text-[#2b2b2b] font-bold text-xl flex w-full text-center">Express Checkout</div>
        <div class="rvvup_express_wrapper flex justify-center w-full">
            <div id="rvvup-express-element" class="rvvup_express_element w-full max-w-[600px] min-w-[200px]"></div>
        </div>
        <div class="rvvup_express_divider_text rvvup_express_text_with_line my-5 text-[#bbb] flex w-full text-center">OR</div>
    </div>
    <script>
        function rvvupExpressButtons() {
            return {
                initRvvup() {
                    const component = Magewire.find('<?= $escaper->escapeJs($block->getNameInLayout()) ?>');
                    let enabledPaymentMethods = [];
                    const applePayExpressEnabled = rvvup_parameters?.settings?.apple_pay?.checkout?.express?.enabled || false;
                    const rvvupCheckout = rvvup_parameters?.checkout;
                    if (applePayExpressEnabled) {
                        enabledPaymentMethods.push('APPLE_PAY');
                    }
                    if (enabledPaymentMethods.length === 0 || !rvvupCheckout) {
                        return;
                    }
                    window.rvvup_sdk.createExpressCheckout({
                        checkoutSessionKey: rvvupCheckout.token,
                        enabledPaymentMethods: enabledPaymentMethods,
                    }).then(expressCheckout => {
                        expressCheckout.on("ready", (data) => {
                            if (data.paymentMethods.length > 0) {
                                document.getElementsByClassName('rvvup_express_container')[0].classList.remove('hidden')
                            }
                        });

                        expressCheckout.on("click", () => {
                            expressCheckout.update(component.quoteData);
                        });
                        expressCheckout.on("shippingAddressChange", async (data) => {
                            if (!data.address || !data.address.countryCode) {
                                return;
                            }
                            await component.shippingAddressChanged(data.address);
                            return component.shippingAddressChangeResult;
                        });
                        expressCheckout.on("shippingMethodChange", async (data) => {
                            if (!data.selected || !data.selected.id) {
                                return;
                            }
                            await component.shippingMethodChanged(data.selected.id);
                            return {
                                total: component.quoteData.total
                            };
                        });
                        expressCheckout.on("beforePaymentAuth", async (data) => {
                            await component.createPaymentSession(rvvupCheckout.id, data)
                            return {
                                paymentSessionId: component.paymentSessionResult.paymentSessionId
                            };
                        });
                        expressCheckout.on("paymentAuthorized", () => {
                            let magewire = document.getElementById('magewire-loader');
                            magewire.children[0].style.display = 'block';
                            window.location.href = component.paymentSessionResult.redirectUrl;
                        });
                        expressCheckout.on("paymentFailed", (data) => {
                            window.dispatchMessages && window.dispatchMessages([{
                                type: 'error',
                                text: 'Payment ' + data.code
                            }], 5000);
                        });
                        expressCheckout.on("error", (data) => {
                            if (data.name === 'RvvupValidationError') {
                                let mappedReason = {
                                    'addressUnserviceable': 'Address is not serviceable',
                                }
                                window.dispatchMessages && window.dispatchMessages([{
                                    type: 'error',
                                    text: mappedReason[data.code] ?? 'Payment Processing Error'
                                }], 5000);
                            }
                        });
                        expressCheckout.mount({
                            selector: "#rvvup-express-element",
                        });
                    }).catch(e => {
                        console.error("Error creating express checkout", e);
                    });
                },
            }
        }
        window.addEventListener('alpine:init', () => Alpine.data('rvvupExpressButtons', rvvupExpressButtons), {once: true});
    </script>
<?php $hyvaCsp->registerInlineScript() ?>

</div>
